namespace ChatService.Infrastructure.Repository.Helper
{
    public static class MIMEAssistant
    {
        private static readonly Dictionary<string, string> MIMETypesDictionary = new Dictionary<string, string>
            {
                {"djv", "image/vnd.djvu"},
                {"djvu", "image/vnd.djvu"},
                {"bmp", "image/bmp"},
                {"mac", "image/x-macpaint"},
                {"pbm", "image/x-portable-bitmap"},
                {"pct", "image/pict"},
                {"ico", "image/x-icon"},
                {"gif", "image/gif"},
                {"ief", "image/ief"},
                {"pgm", "image/x-portable-graymap"},
                {"pic", "image/pict"},
                {"svg", "image/svg+xml"},
                {"wbmp", "image/vnd.wap.wbmp"},
                {"xbm", "image/x-xbitmap"},
                {"xwd", "image/x-xwindowdump"},
                {"xpm", "image/x-xpixmap"},
                {"png", "image/png"},
                {"pnm", "image/x-portable-anymap"},
                {"pnt", "image/x-macpaint"},
                {"pntg", "image/x-macpaint"},
                {"qti", "image/x-quicktime"},
                {"qtif", "image/x-quicktime"},
                {"ras", "image/x-cmu-raster"},
                {"rgb", "image/x-rgb"},
                {"tif", "image/tiff"},
                {"tiff", "image/tiff"},
                {"ppm", "image/x-portable-pixmap"},
                {"jp2", "image/jp2"},
                {"jpe", "image/jpeg"},
                {"jpeg", "image/jpeg"},
                {"pict", "image/pict"},
                {"cgm", "image/cgm"},
                {"jpg", "image/jpeg"},
             
                {"aif", "audio/x-aiff"},
                {"aifc", "audio/x-aiff"},
                {"aiff", "audio/x-aiff"},
                {"au", "audio/basic"},
                {"m3u", "audio/x-mpegurl"},
                {"m4a", "audio/mp4a-latm"},
                {"m4b", "audio/mp4a-latm"},
                {"m4p", "audio/mp4a-latm"},
                {"wav", "audio/x-wav"},
                {"kar", "audio/midi"},
                {"mp2", "audio/mpeg"},
                {"mp3", "audio/mpeg"},
                {"mid", "audio/midi"},
                {"midi", "audio/midi"},
                {"mpga", "audio/mpeg"},
                {"ra", "audio/x-pn-realaudio"},
                {"ram", "audio/x-pn-realaudio"},
                {"snd", "audio/basic"},
             
                {"dif", "video/x-dv"},
                {"mov", "video/quicktime"},
                {"movie", "video/x-sgi-movie"},
                {"m4u", "video/vnd.mpegurl"},
                {"m4v", "video/x-m4v"},
                {"mp4", "video/mp4"},
                {"mpe", "video/mpeg"},
                {"mpeg", "video/mpeg"},
                {"mpg", "video/mpeg"},
                {"mxu", "video/vnd.mpegurl"},
                {"qt", "video/quicktime"},
                {"avi", "video/x-msvideo"},
                {"dv", "video/x-dv"},
             
                {"asc", "text/plain"},
                {"css", "text/css"},
                {"htm", "text/html"},
                {"html", "text/html"},
                {"ics", "text/calendar"},
                {"ifb", "text/calendar"},
                {"rtf", "text/rtf"},
                {"rtx", "text/richtext"},
                {"sgm", "text/sgml"},
                {"sgml", "text/sgml"},
                {"tsv", "text/tab-separated-values"},
                {"txt", "text/plain"},
                {"wml", "text/vnd.wap.wml"},
                {"wmls", "text/vnd.wap.wmlscript"},
             
                {"dcr", "application/x-director"},
                {"tr", "application/x-troff"},
                {"dir", "application/x-director"},
                {"dll", "application/octet-stream"},
                {"class", "application/octet-stream"},
                {"cpio", "application/x-cpio"},
                {"cpt", "application/mac-compactpro"},
                {"bcpio", "application/x-bcpio"},
                {"bin", "application/octet-stream"},
                {"cdf", "application/x-netcdf"},
                {"csh", "application/x-csh"},
                {"pgn", "application/x-chess-pgn"},
                {"xsl", "application/xml"},
                {"xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
                {"dmg", "application/octet-stream"},
                {"dms", "application/octet-stream"},
                {"doc", "application/msword"},
                {"atom", "application/atom+xml"},
                {"docx","application/vnd.openxmlformats-officedocument.wordprocessingml.document"},
                {"dotx", "application/vnd.openxmlformats-officedocument.wordprocessingml.template"},
                {"docm","application/vnd.ms-word.document.macroEnabled.12"},
                {"dotm","application/vnd.ms-word.template.macroEnabled.12"},
                {"dtd", "application/xml-dtd"},
                {"dvi", "application/x-dvi"},
                {"dxr", "application/x-director"},
                {"eps", "application/postscript"},
                {"etx", "text/x-setext"},
                {"exe", "application/octet-stream"},
                {"ez", "application/andrew-inset"},
                {"gram", "application/srgs"},
                {"grxml", "application/srgs+xml"},
                {"gtar", "application/x-gtar"},
                {"hdf", "application/x-hdf"},
                {"hqx", "application/mac-binhex40"},
                {"ice", "x-conference/x-cooltalk"},
                {"iges", "model/iges"},
                {"igs", "model/iges"},
                {"jnlp", "application/x-java-jnlp-file"},
                {"js", "application/x-javascript"},
                {"latex", "application/x-latex"},
                {"lha", "application/octet-stream"},
                {"lzh", "application/octet-stream"},
                {"man", "application/x-troff-man"},
                {"mathml", "application/mathml+xml"},
                {"me", "application/x-troff-me"},
                {"mesh", "model/mesh"},
                {"mif", "application/vnd.mif"},
                {"ms", "application/x-troff-ms"},
                {"msh", "model/mesh"},
                {"nc", "application/x-netcdf"},
                {"oda", "application/oda"},
                {"ogg", "application/ogg"},
                {"pdb", "chemical/x-pdb"},
                {"pdf", "application/pdf"},
                {"ppt", "application/vnd.ms-powerpoint"},
                {"pptx","application/vnd.openxmlformats-officedocument.presentationml.presentation"},
                {"potx","application/vnd.openxmlformats-officedocument.presentationml.template"},
                {"ppsx","application/vnd.openxmlformats-officedocument.presentationml.slideshow"},
                {"ppam","application/vnd.ms-powerpoint.addin.macroEnabled.12"},
                {"pptm","application/vnd.ms-powerpoint.presentation.macroEnabled.12"},
                {"potm","application/vnd.ms-powerpoint.template.macroEnabled.12"},
                {"ppsm","application/vnd.ms-powerpoint.slideshow.macroEnabled.12"},
                {"ps", "application/postscript"},
                {"rdf", "application/rdf+xml"},
                {"rm", "application/vnd.rn-realmedia"},
                {"roff", "application/x-troff"},
                {"sh", "application/x-sh"},
                {"shar", "application/x-shar"},
                {"silo", "model/mesh"},
                {"sit", "application/x-stuffit"},
                {"skd", "application/x-koan"},
                {"skm", "application/x-koan"},
                {"skp", "application/x-koan"},
                {"skt", "application/x-koan"},
                {"smi", "application/smil"},
                {"smil", "application/smil"},
                {"so", "application/octet-stream"},
                {"spl", "application/x-futuresplash"},
                {"src", "application/x-wais-source"},
                {"sv4cpio", "application/x-sv4cpio"},
                {"sv4crc", "application/x-sv4crc"},
                {"swf", "application/x-shockwave-flash"},
                {"t", "application/x-troff"},
                {"tar", "application/x-tar"},
                {"tcl", "application/x-tcl"},
                {"tex", "application/x-tex"},
                {"texi", "application/x-texinfo"},
                {"texinfo", "application/x-texinfo"},
                {"ustar", "application/x-ustar"},
                {"vcd", "application/x-cdlink"},
                {"vrml", "model/vrml"},
                {"vxml", "application/voicexml+xml"},
                {"wbmxl", "application/vnd.wap.wbxml"},
                {"wmlc", "application/vnd.wap.wmlc"},
                {"wmlsc", "application/vnd.wap.wmlscriptc"},
                {"wrl", "model/vrml"},
                {"xht", "application/xhtml+xml"},
                {"xhtml", "application/xhtml+xml"},
                {"xls", "application/vnd.ms-excel"},
                {"xml", "application/xml"},
                {"xltx","application/vnd.openxmlformats-officedocument.spreadsheetml.template"},
                {"xlsm","application/vnd.ms-excel.sheet.macroEnabled.12"},
                {"xltm","application/vnd.ms-excel.template.macroEnabled.12"},
                {"xlam","application/vnd.ms-excel.addin.macroEnabled.12"},
                {"xlsb","application/vnd.ms-excel.sheet.binary.macroEnabled.12"},
                {"xslt", "application/xslt+xml"},
                {"xul", "application/vnd.mozilla.xul+xml"},
                {"xyz", "chemical/x-xyz"},
                {"zip", "application/zip"}
              };
             
        public static string GetMIMEType(string fileName)
        {
            //get file extension
            string extension = Path.GetExtension(fileName).ToLowerInvariant();

            if (extension.Length > 0 &&
                MIMETypesDictionary.ContainsKey(extension.Remove(0, 1)))
            {
                return MIMETypesDictionary[extension.Remove(0, 1)];
            }
            return "unknown/unknown";
        }
    }
}